server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: master-service
          uri: lb://master-service
          predicates:
            - Path=/api/master/**
          filters:
            - RewritePath=/api/master(?<segment>/?.*), /$\{segment}

        - id: sub-service
          uri: lb://sub-service
          predicates:
            - Path=/api/sub/**
          filters:
            - RewritePath=/api/sub(?<segment>/?.*), /$\{segment}

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notification/**
          filters:
            - RewritePath=/api/notification(?<segment>/?.*), /$\{segment}
